"""
/***************************************************************************
 RNA
                                 A QGIS plugin
 RNA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-02
        copyright            : (C) 2025 by C.A.S
        email                : rna@qgis.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

import logging
import sys
import traceback
from pathlib import Path
from typing import Any

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(name)s] %(levelname)s: %(message)s',
    datefmt='%H:%M:%S',
)

logger = logging.getLogger(__name__)


# noinspection PyPep8Naming
def classFactory(iface: Any) -> Any:  # pylint: disable=invalid-name
    """Load RNA class from file RNA.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    # Ensure RNA plugin dir is on sys.path so 'app' subpackage
    # resolves even under QGIS's import hook on Python 3.14
    _dir = str(Path(__file__).parent)
    if _dir not in sys.path:
        sys.path.insert(0, _dir)

    try:
        from .app.main import RNA

        return RNA(iface)
    except ImportError:
        logger.error('ImportError in classFactory:\n%s', traceback.format_exc())
        raise
