
"""
/***************************************************************************
 RNA
                                 A QGIS plugin
 RNA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-02
        copyright            : (C) 2025 by C.A.S
        email                : rna@qgis.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import logging
from typing import Any

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(name)s] %(levelname)s: %(message)s',
    datefmt='%H:%M:%S',
)


# noinspection PyPep8Naming
def classFactory(iface: Any) -> Any:  # pylint: disable=invalid-name
    """Load RNA class from file RNA.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .app.main import RNA
    return RNA(iface)
