"""Plugin-level re-exports bridging the app package and legacy imports."""
# pylint: disable=unused-import

from .app.shared.constants import (
    PLUGIN_DIR, SRID, CRS, COOKIE_FILE, DATABASE_FILE,
    QGIS_CONFIG_FILE, STYLE_QML, DEFAULT_STYLE_DIR, CUSTOM_STYLE_DIR,
    TEMPLATE_REP, TEMPLATE_CMD, TMP_JSON, MAP_PNG, VIEWS_SQL,
    MEMORY_PROVIDER, NOTIFY_DURATION,
    MAP_A3_TEMPLATE, MAP_A0_TEMPLATE,
    SITUATION_PNG, NORTH_ARROW_SVG, SYMBOLS_SVG, SCALE_BAR_SVG, CHART_SVG,
    ICON_PNG,
    REPORTING_SCRIPT,
    LAYER_ROADS, LAYER_FACILITIES, LAYER_SUBDIVISIONS,
    LAYER_MUNICIPALITY, LAYER_ZONES, LAYER_NUMBERING, LAYER_PANELS,
    LAYER_NAMES, LAYER_KEY,
    PAN_MOUNTED, PAN_PLANNED, PAN_TO_MOVE, PAN_TO_FIX,
    NUM_PLANNED, NO_ACTIVITY,
    THEME_DARK, THEME_LIGHT, AVAILABLE_LOCALES,
    SETTINGS_ORG, SETTINGS_APP, SETTINGS_KEY_THEME, SETTINGS_KEY_LOCALE,
    WILAYAS_JSON, DAIRA_JSON, COMMUNES_JSON, COMMUNES_GEOJSON, COMMUNES_DB, TEMPLATE_DATA_DIR,
)
from .app.core.config import (
    DARK_QSS, DARK_QSS_DIALOG, LIGHT_QSS, LIGHT_QSS_DIALOG,
    THEMES, DEFAULT_THEME,
    get_theme_qss, get_dialog_qss, find_mod_spatialite_dll,
)
from .app.shared.utils import (
    validate_text, current_locale, locale_value,
    current_theme, get_qgis_python,
    _SUBPROCESS_FLAGS,
)
