"""Plugin-level re-exports bridging the app package and legacy imports."""
# ruff: noqa: F401
# pylint: disable=unused-import

from .app.core.config import (
    DARK_QSS,
    DARK_QSS_DIALOG,
    DEFAULT_THEME,
    LIGHT_QSS,
    LIGHT_QSS_DIALOG,
    THEMES,
    find_mod_spatialite_dll,
    get_dialog_qss,
    get_theme_qss,
)
from .app.shared.constants import (
    AVAILABLE_LOCALES,
    CHART_SVG,
    COMMUNES_DB,
    COMMUNES_GEOJSON,
    COMMUNES_JSON,
    COOKIE_FILE,
    CRS,
    CUSTOM_STYLE_DIR,
    DAIRA_JSON,
    DATABASE_FILE,
    DEFAULT_STYLE_DIR,
    ICON_PNG,
    LAYER_FACILITIES,
    LAYER_KEY,
    LAYER_MUNICIPALITY,
    LAYER_NAMES,
    LAYER_NUMBERING,
    LAYER_PANELS,
    LAYER_ROADS,
    LAYER_SUBDIVISIONS,
    LAYER_ZONES,
    MAP_A0_TEMPLATE,
    MAP_A3_TEMPLATE,
    MAP_PNG,
    MEMORY_PROVIDER,
    NO_ACTIVITY,
    NORTH_ARROW_SVG,
    NOTIFY_DURATION,
    NUM_PLANNED,
    PAN_MOUNTED,
    PAN_PLANNED,
    PAN_TO_FIX,
    PAN_TO_MOVE,
    PLUGIN_DIR,
    QGIS_CONFIG_FILE,
    REPORTING_SCRIPT,
    SCALE_BAR_SVG,
    SETTINGS_APP,
    SETTINGS_KEY_LOCALE,
    SETTINGS_KEY_THEME,
    SETTINGS_ORG,
    SITUATION_PNG,
    SRID,
    STYLE_QML,
    SYMBOLS_SVG,
    TEMPLATE_CMD,
    TEMPLATE_DATA_DIR,
    TEMPLATE_REP,
    THEME_DARK,
    THEME_LIGHT,
    TMP_JSON,
    VIEWS_SQL,
    WILAYAS_JSON,
)
from .app.shared.utils import (
    _SUBPROCESS_FLAGS,
    current_locale,
    current_theme,
    get_qgis_python,
    locale_value,
    validate_text,
)
