import sys as _sys
import os as _os
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))

try:
    from ..app.shared.constants import (
        PLUGIN_DIR, SRID, CRS,
        COOKIE_FILE, DATABASE_FILE, AUTH_DATABASE_FILE, QGIS_CONFIG_FILE,
        STYLE_QML, DEFAULT_STYLE_DIR, CUSTOM_STYLE_DIR,
        TEMPLATE_REP, TEMPLATE_CMD, TMP_JSON, REPORTING_SCRIPT,
        MAP_PNG, ICON_PNG, VIEWS_SQL, TEMPLATE_DATA_DIR,
        MAP_A3_TEMPLATE, MAP_A0_TEMPLATE, SITUATION_PNG,
        NORTH_ARROW_SVG, SYMBOLS_SVG, SCALE_BAR_SVG, CHART_SVG,
        MEMORY_PROVIDER, NOTIFY_DURATION,
        LAYER_MUNICIPALITY, LAYER_ROADS, LAYER_FACILITIES,
        LAYER_SUBDIVISIONS, LAYER_ZONES, LAYER_NUMBERING, LAYER_PANELS,
        LAYER_NAMES, LAYER_KEY, LAYER_MODEL,
        PAN_MOUNTED, PAN_PLANNED, PAN_TO_MOVE, PAN_TO_FIX,
        NUM_PLANNED, NO_ACTIVITY, DEFAULT_PANEL_DIM,
        SETTINGS_ORG, SETTINGS_APP, SETTINGS_KEY_THEME, SETTINGS_KEY_LOCALE,
        THEME_DARK, THEME_LIGHT, AVAILABLE_LOCALES,
    )
    from ..app.core.config import (
        DARK_BG, DARK_SURFACE, DARK_OVERLAY, DARK_BORDER,
        DARK_TEXT, DARK_TEXT_SEC, DARK_ACCENT, DARK_ACCENT_HOVER,
        DARK_SUCCESS, DARK_DANGER, DARK_SELECTION,
        LIGHT_BG, LIGHT_SURFACE, LIGHT_OVERLAY, LIGHT_BORDER,
        LIGHT_TEXT, LIGHT_TEXT_SEC, LIGHT_ACCENT, LIGHT_ACCENT_HOVER,
        LIGHT_SUCCESS, LIGHT_DANGER, LIGHT_SELECTION,
        DARK_QSS, DARK_QSS_DIALOG, LIGHT_QSS, LIGHT_QSS_DIALOG,
        THEMES, DEFAULT_THEME,
        get_theme_qss, get_dialog_qss, find_mod_spatialite_dll,
    )
    from ..app.shared.utils import (
        validate_text, current_locale, locale_value,
        current_theme, get_qgis_python,
        _SUBPROCESS_FLAGS,
    )
except ImportError:
    from app.shared.constants import (
        PLUGIN_DIR, SRID, CRS,
        COOKIE_FILE, DATABASE_FILE, AUTH_DATABASE_FILE, QGIS_CONFIG_FILE,
        STYLE_QML, DEFAULT_STYLE_DIR, CUSTOM_STYLE_DIR,
        TEMPLATE_REP, TEMPLATE_CMD, TMP_JSON, REPORTING_SCRIPT,
        MAP_PNG, ICON_PNG, VIEWS_SQL, TEMPLATE_DATA_DIR,
        MAP_A3_TEMPLATE, MAP_A0_TEMPLATE, SITUATION_PNG,
        NORTH_ARROW_SVG, SYMBOLS_SVG, SCALE_BAR_SVG, CHART_SVG,
        MEMORY_PROVIDER, NOTIFY_DURATION,
        LAYER_MUNICIPALITY, LAYER_ROADS, LAYER_FACILITIES,
        LAYER_SUBDIVISIONS, LAYER_ZONES, LAYER_NUMBERING, LAYER_PANELS,
        LAYER_NAMES, LAYER_KEY, LAYER_MODEL,
        PAN_MOUNTED, PAN_PLANNED, PAN_TO_MOVE, PAN_TO_FIX,
        NUM_PLANNED, NO_ACTIVITY, DEFAULT_PANEL_DIM,
        SETTINGS_ORG, SETTINGS_APP, SETTINGS_KEY_THEME, SETTINGS_KEY_LOCALE,
        THEME_DARK, THEME_LIGHT, AVAILABLE_LOCALES,
    )
    from app.core.config import (
        DARK_BG, DARK_SURFACE, DARK_OVERLAY, DARK_BORDER,
        DARK_TEXT, DARK_TEXT_SEC, DARK_ACCENT, DARK_ACCENT_HOVER,
        DARK_SUCCESS, DARK_DANGER, DARK_SELECTION,
        LIGHT_BG, LIGHT_SURFACE, LIGHT_OVERLAY, LIGHT_BORDER,
        LIGHT_TEXT, LIGHT_TEXT_SEC, LIGHT_ACCENT, LIGHT_ACCENT_HOVER,
        LIGHT_SUCCESS, LIGHT_DANGER, LIGHT_SELECTION,
        DARK_QSS, DARK_QSS_DIALOG, LIGHT_QSS, LIGHT_QSS_DIALOG,
        THEMES, DEFAULT_THEME,
        get_theme_qss, get_dialog_qss, find_mod_spatialite_dll,
    )
    from app.shared.utils import (
        validate_text, current_locale, locale_value,
        current_theme, get_qgis_python,
        _SUBPROCESS_FLAGS,
    )
