"""
/***************************************************************************
 RNA
                                 A QGIS plugin
 RNA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-01-02
        git sha              : $Format:%H$
        copyright            : (C) 2025 by C.A.S
        email                : rna@qgis.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from typing import Any
import logging

from qgis.PyQt.QtCore import QSettings, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QDockWidget, QMessageBox

logger = logging.getLogger(__name__)

import os

from .constants import ICON_PNG, current_locale
from .scripts.lookup_data import get_string
from .RNA_dialog import RNADialog
from qgis.core import QgsApplication


class RNA:
    """QGIS Plugin Implementation."""

    def __init__(self, iface) -> None:

        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface

        QgsApplication.setPrefixPath(os.getenv('QGIS_BASE_PATH', '/usr'), True)

        # Set the SVG path
        svg_path = os.path.join(
            os.getenv('QGIS_BASE_PATH', '/usr'),
            'apps', 'qgis', 'svg'
        )

        QgsApplication.setDefaultSvgPaths([svg_path])
        QgsApplication.instance().setSvgPaths([svg_path])

        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        settings = QSettings()
        settings.beginGroup('digitizing')
        settings.setValue('disable-enter-attribute-values-dialog', True)
        settings.endGroup()

        from .constants import SETTINGS_ORG, SETTINGS_APP, SETTINGS_KEY_LOCALE
        self._locale_code = QSettings(SETTINGS_ORG, SETTINGS_APP).value(
            SETTINGS_KEY_LOCALE, '')
        if not self._locale_code:
            locale_val = QSettings().value('locale/userLocale')
            self._locale_code = locale_val[0:2] if locale_val else 'en'

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr('&RNA')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message) -> str:
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('RNA', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None) -> Any:
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self) -> None:
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        img_ico = ICON_PNG
        self.add_action(
            img_ico,
            text=self.tr(''),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self) -> None:
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr('&RNA'),
                action)
            self.iface.removeToolBarIcon(action)



    def run(self) -> None:
        """Run method that performs all the real work"""

        logger.info("run() called, first_start=%s", self.first_start)

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only
        # load when the plugin is started
        if self.first_start is True:
            self.first_start = False
            try:
                self.dlg = RNADialog(self.iface)
                logger.info("RNADialog created successfully")
            except Exception as e:
                logger.exception("Failed to create RNADialog: %s", e)
                loc = current_locale()
                QMessageBox.critical(
                    None, get_string("RNA Plugin Error", loc),
                    get_string("Failed to create dialog", loc) + f"\n\n{get_string('Check the QGIS log for details.', loc)}",
                )
                return

            self.dock_widget = QDockWidget(
                get_string("RNA Plugin", current_locale()), self.iface.mainWindow()
            )  # Give a title to the docked widget
            self.dock_widget.setWidget(
                self.dlg
            )  # Set the dialog as the widget for the dock

            # Add the dock widget to the interface (e.g., on the left side)
            self.iface.addDockWidget(Qt.LeftDockWidgetArea, self.dock_widget)

            # Show the dock widget
            self.dock_widget.show()

        # show the dialog
        if hasattr(self, 'dock_widget'):
            self.dock_widget.raise_()
            self.dock_widget.show()
