"""
/***************************************************************************
 RNADialog
                                 A QGIS plugin
 RNA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-01-02
        git sha              : $Format:%H$
        copyright            : (C) 2025 by C.A.S
        email                : rna@qgis.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
from PyQt5.QtCore import Qt, QDate, QSettings, QSize
from PyQt5.QtWidgets import (
    QApplication, QCheckBox, QDialog, QGroupBox, QLabel,
    QPushButton, QVBoxLayout, QHBoxLayout, QComboBox, QWidget,
    QDateEdit, QFormLayout, QLayout, QLineEdit, QSizePolicy,
)
from qgis.PyQt import uic
from .gui.ui_fillers import (
    fill_wilayas_list, fill_paper, fill_road_type, fill_numbering_state,
    fill_mounting_status, fill_subdivision_type, fill_type_zone,
    fill_road_reference, fill_panel_reference, fill_org_category,
    fill_type_org, fill_activity_category, fill_type_act,
)

from .constants import (
    THEME_DARK, THEME_LIGHT, THEMES, DEFAULT_THEME,
    get_theme_qss, get_dialog_qss,
    SETTINGS_ORG, SETTINGS_APP, SETTINGS_KEY_THEME, SETTINGS_KEY_LOCALE,
    AVAILABLE_LOCALES, current_locale,
)
from .scripts.lookup_data import get_string, apply_widget_texts, clear_i18n_cache
import logging
logger = logging.getLogger(__name__)

# This loads your .ui file so that PyQt can populate your plugin
# with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'gui', 'RNA_dialog_base.ui'))

from .mixins.chart_mixin import ChartMixin
from .mixins.map_tools_mixin import MapToolsMixin
from .mixins.auth_mixin import AuthMixin
from .mixins.layer_ops_mixin import LayerOpsMixin
from .mixins.layer_draw_mixin import LayerDrawMixin
from .mixins.layer_edit_mixin import LayerEditMixin
from .mixins.backup_mixin import BackupMixin
from .mixins.symbol_export_mixin import SymbolExportMixin
from .mixins.import_export_mixin import ImportExportMixin
from .mixins.report_mixin import ReportMixin


class RNADialog(
    QDialog, FORM_CLASS, ChartMixin, MapToolsMixin,
    AuthMixin, LayerOpsMixin, LayerDrawMixin, LayerEditMixin,
    BackupMixin, SymbolExportMixin, ImportExportMixin, ReportMixin,
):
    """Main dialog for the RNA QGIS plugin."""
    def __init__(self, iface, parent=None) -> None:
        """Constructor."""
        super(RNADialog, self).__init__(parent)
        self.iface = iface
        self._tr_locale = current_locale()
        if self._tr_locale == 'ar':
            QApplication.setLayoutDirection(Qt.RightToLeft)
        else:
            QApplication.setLayoutDirection(Qt.LeftToRight)
        try:
            self.setupUi(self)
        except Exception as e:
            logger.exception("setupUi failed: %s", e)
            raise

        self._init_state()
        self._connect_signals()
        self._populate_combos()
        self.fill_map_options()

        self.iface.mapCanvas().setContextMenuPolicy(Qt.CustomContextMenu)
        self.iface.mapCanvas().customContextMenuRequested.connect(
            self.on_edition_release
        )
        self.iface.mapCanvas().mapToolSet.connect(self._on_map_tool_changed)

        self._current_theme = DEFAULT_THEME
        self.setup_settings_ui()
        self._apply_ui_polish()
        apply_widget_texts(self, self._tr_locale)
        self.apply_theme()

    def _init_state(self) -> None:
        self.sat_view = None
        self.rast = None
        self.ln = None
        self.type_plan = ""
        self.type_to_hide = ""
        self.measure_tool = None
        self.measure_tool2 = None
        self.identify_tool = None
        self.identify_tool2 = None
        self.popup_dialog = None
        self.current_user = None
        self.update_object = {}
        self.update_only_form = {}
        self.dateEdit.setDate(QDate.currentDate())

    def _connect_signals(self) -> None:
        self.add_u.clicked.connect(lambda: self.public_route('add_usr'))
        self.submit_usr.clicked.connect(self.submit_add_usr)
        self.sign_in_user.clicked.connect(self.login_user)
        self.wilaya_list.currentIndexChanged.connect(self.on_select_wilaya)
        self.cat_org.currentIndexChanged.connect(self.on_select_catOrg)
        self.cat_act.currentIndexChanged.connect(self.on_select_catAct)
        self.abort_uc.clicked.connect(lambda: self.public_route('login'))

        # Consolidated toolbar
        self.draw_btn.clicked.connect(lambda: self.start_drawing())
        self.select_btn.clicked.connect(lambda: self.start_selecting())
        self.edit_btn.clicked.connect(lambda: self.start_editing())
        self.layer_selector.currentIndexChanged.connect(
            self._on_layer_changed)

        # Per-entity submit and list
        self.submit_zone.clicked.connect(self.add_zone)
        self.submit_voie.clicked.connect(lambda: self.add_road())
        self.submit_org.clicked.connect(lambda: self.add_organization())
        self.submit_city.clicked.connect(self.add_city)
        self.submit_num.clicked.connect(self.add_numbering)
        self.submit_pan.clicked.connect(self.add_panel)
        self.list_voie.clicked.connect(self.list_roads)
        self.list_org.clicked.connect(self.list_organizations)
        self.list_cities.clicked.connect(self.list_subdivisions)
        self.list_num.clicked.connect(self.list_numberings)
        self.list_pan.clicked.connect(self.list_panels)

        # Reference selection (numbering + panels)
        self.select_ref.clicked.connect(self.select_ref_handler)
        self.select_ref2.clicked.connect(self.select_ref_handler2)
        self.page_num.keyPressEvent = lambda e: self.key_press_event(e)
        self.page_pan.keyPressEvent = lambda e: self.key_press_event2(e)

        # Measure tools
        self.mesure_dist.clicked.connect(self.measure_distance)
        self.mesure_dist_2.clicked.connect(self.measure_distance2)

        # Map management
        self.bc.clicked.connect(self.bon_commande)
        self.print.clicked.connect(self.export_to_image1)
        self.pan.clicked.connect(self.carte_pano1)
        self.num_carte.clicked.connect(self.carte_num1)

        # Utilities
        self.logout_btn.clicked.connect(lambda: self.close())
        self.backup_db.clicked.connect(self.backup)
        self.restore_db.clicked.connect(self.restore_database)
        self.report.clicked.connect(self.gen_report)
        self.menu.currentChanged.connect(self.on_opt_selected)

    def _on_layer_changed(self, index: int) -> None:
        """Switch the form stack page when the layer selector changes."""
        self.form_stack.setCurrentIndex(index)

    def _populate_combos(self) -> None:
        fill_paper(self.paper)
        fill_wilayas_list(self.wilaya_list)
        fill_road_type(self.type_voie)
        fill_numbering_state(self.num_etat)
        fill_mounting_status(self.etat_mont)
        fill_subdivision_type(self.type_city)
        fill_type_zone(self.type_zone)
        fill_road_reference(self.dyn_ref)
        fill_panel_reference(self.dyn_ref2)

    LAYER_INDEX_MAP = [
        "المناطق", "الطرق", "المرافق",
        "التجزئات", "الترقيم", "اللوحات",
    ]

    def _current_layer_name(self) -> str:
        idx = self.layer_selector.currentIndex()
        if 0 <= idx < len(self.LAYER_INDEX_MAP):
            return self.LAYER_INDEX_MAP[idx]
        return self.LAYER_INDEX_MAP[0]

    def _tr(self, source: str) -> str:
        return get_string(source, self._tr_locale)

    def setup_settings_ui(self) -> None:
        s = QSettings(SETTINGS_ORG, SETTINGS_APP)

        self._settings_group = QGroupBox(get_string("الإعدادات", self._tr_locale))
        self._settings_group.setObjectName("_settings_group")
        self._settings_group.setLayout(QVBoxLayout())

        theme_row = QHBoxLayout()
        self._theme_label = QLabel(get_string("المظهر:", self._tr_locale))
        self._theme_label.setObjectName("_theme_label")
        theme_row.addWidget(self._theme_label)
        self._theme_combo = QComboBox()
        self._theme_combo.addItem(THEME_DARK)
        self._theme_combo.addItem(THEME_LIGHT)
        self._theme_combo.currentTextChanged.connect(self._on_theme_changed)
        saved_theme = s.value(SETTINGS_KEY_THEME, DEFAULT_THEME)
        idx = self._theme_combo.findText(saved_theme)
        if idx >= 0:
            self._theme_combo.setCurrentIndex(idx)
        self._current_theme = self._theme_combo.currentText()
        theme_row.addWidget(self._theme_combo)
        self._settings_group.layout().addLayout(theme_row)

        locale_row = QHBoxLayout()
        self._locale_label = QLabel(get_string("اللغة:", self._tr_locale))
        self._locale_label.setObjectName("_locale_label")
        locale_row.addWidget(self._locale_label)
        self._locale_combo = QComboBox()
        for code, label in AVAILABLE_LOCALES:
            self._locale_combo.addItem(label, code)
        self._locale_combo.currentIndexChanged[int].connect(self._on_locale_changed)
        self._locale_combo.blockSignals(True)
        saved_locale = s.value(SETTINGS_KEY_LOCALE, "")
        if saved_locale:
            li = self._locale_combo.findData(saved_locale)
            if li >= 0:
                self._locale_combo.setCurrentIndex(li)
        self._locale_combo.blockSignals(False)
        locale_row.addWidget(self._locale_combo)
        self._settings_group.layout().addLayout(locale_row)

        self.scrollAreaWidgetContents_2.layout().addWidget(self._settings_group)

    def _on_theme_changed(self, theme_name: str) -> None:
        self._current_theme = theme_name
        s = QSettings(SETTINGS_ORG, SETTINGS_APP)
        s.setValue(SETTINGS_KEY_THEME, theme_name)
        self.apply_theme()

    def _on_locale_changed(self, idx: int) -> None:
        code = self._locale_combo.currentData()
        if not code:
            return
        s = QSettings(SETTINGS_ORG, SETTINGS_APP)
        s.setValue(SETTINGS_KEY_LOCALE, code)
        self._tr_locale = code
        clear_i18n_cache()
        apply_widget_texts(self, code)
        fill_wilayas_list(self.wilaya_list)
        fill_road_type(self.type_voie)
        fill_type_zone(self.type_zone)
        fill_subdivision_type(self.type_city)
        fill_mounting_status(self.etat_mont)
        fill_numbering_state(self.num_etat)
        fill_paper(self.paper)
        fill_org_category(self.cat_org)
        fill_activity_category(self.cat_act)
        if code == 'ar':
            QApplication.setLayoutDirection(Qt.RightToLeft)
        else:
            QApplication.setLayoutDirection(Qt.LeftToRight)

    def _set_button_roles(self) -> None:
        primary_buttons = {
            'sign_in_user',
            'submit_usr',
            'submit_zone',
            'submit_voie',
            'submit_org',
            'submit_city',
            'submit_num',
            'submit_pan',
            'report',
        }
        danger_buttons = {'logout_btn', 'abort_uc'}
        tool_prefixes = ('draw_', 'select_', 'edit_')

        for button in self.findChildren(QPushButton):
            name = button.objectName()
            if name in primary_buttons:
                button.setProperty('role', 'primary')
            elif name in danger_buttons:
                button.setProperty('role', 'danger')
            elif any(name.startswith(prefix) for prefix in tool_prefixes):
                button.setProperty('role', 'tool')
                button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
            else:
                button.setProperty('role', 'ghost')

            button.setMinimumHeight(max(button.minimumHeight(), 34))
            button.setMaximumWidth(16777215)
            button.setIconSize(QSize(16, 16))

    def _apply_ui_polish(self) -> None:
        self.setObjectName('rnaMainDialog')
        self.setSizeGripEnabled(True)
        self.setMinimumSize(640, 680)
        self.setMaximumSize(16777215, 16777215)
        if self.width() < 680:
            self.resize(680, 720)

        self.router.setMaximumHeight(16777215)
        self.groupBox.setMaximumSize(16777215, 16777215)
        self.groupBox.setMinimumSize(500, 390)
        self.groupBox.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)

        self.menu.setDocumentMode(True)
        self.menu.setUsesScrollButtons(True)
        tab_bar = self.menu.tabBar()
        tab_bar.setExpanding(False)
        tab_bar.setElideMode(Qt.ElideRight)

        for frame_name, role in {
            'frame_12': 'header',
            'frame_8': 'toolbar',
            'frame_9': 'footer',
        }.items():
            frame = getattr(self, frame_name, None)
            if frame is not None:
                frame.setProperty('surfaceRole', role)

        for layout in self.findChildren(QLayout):
            if isinstance(layout, QFormLayout):
                if layout.horizontalSpacing() < 12:
                    layout.setHorizontalSpacing(12)
                if layout.verticalSpacing() < 10:
                    layout.setVerticalSpacing(10)
            elif layout.spacing() < 8:
                layout.setSpacing(8)

        for widget in self.findChildren(QLineEdit):
            widget.setMinimumHeight(max(widget.minimumHeight(), 34))
            widget.setMaximumWidth(16777215)
            widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)

        for widget in self.findChildren(QComboBox):
            widget.setMinimumHeight(max(widget.minimumHeight(), 34))
            widget.setMaximumWidth(16777215)
            widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)

        for widget in self.findChildren(QDateEdit):
            widget.setMinimumHeight(max(widget.minimumHeight(), 34))
            widget.setMaximumWidth(16777215)
            widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)

        self._set_button_roles()

    def apply_theme(self) -> None:
        theme = self._current_theme
        qss = get_theme_qss(theme)
        self.setStyleSheet(qss)
