"""
/***************************************************************************
 RNADialog
                                 A QGIS plugin
 RNA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-01-02
        git sha              : $Format:%H$
        copyright            : (C) 2025 by C.A.S
        email                : rna@qgis.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
from PyQt5.QtCore import Qt, QDate, QSettings
from PyQt5.QtWidgets import (
    QCheckBox, QDialog, QGroupBox, QLabel, QPushButton,
    QVBoxLayout, QHBoxLayout, QComboBox, QWidget,
)
from qgis.PyQt import uic
from .gui.ui_fillers import (
    fill_wilayas_list, fill_paper, fill_road_type, fill_numbering_state,
    fill_mounting_status, fill_subdivision_type, fill_type_zone,
    fill_road_reference, fill_panel_reference, fill_org_category,
    fill_type_org, fill_activity_category, fill_type_act,
)
from .db.writers import (
    add_road_type, add_type_zone, add_subdivision_type,
    add_organization_type, add_activity_type,
)
from .constants import (
    validate_text, THEME_DARK, THEME_LIGHT, THEMES, DEFAULT_THEME,
    get_theme_qss, get_dialog_qss,
    SETTINGS_ORG, SETTINGS_APP, SETTINGS_KEY_THEME, SETTINGS_KEY_LOCALE,
    AVAILABLE_LOCALES,
)
from .i18n import tr as _i18n_tr
import logging
logger = logging.getLogger(__name__)


def _load_locale() -> str:
    s = QSettings(SETTINGS_ORG, SETTINGS_APP)
    locale = s.value(SETTINGS_KEY_LOCALE, '')
    if not locale:
        locale_val = QSettings().value('locale/userLocale')
        locale = locale_val[0:2] if locale_val else 'en'
    return locale

# This loads your .ui file so that PyQt can populate your plugin
# with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'gui', 'RNA_dialog_base.ui'))

from .mixins.chart_mixin import ChartMixin
from .mixins.map_tools_mixin import MapToolsMixin
from .mixins.auth_mixin import AuthMixin
from .mixins.layer_ops_mixin import LayerOpsMixin
from .mixins.layer_draw_mixin import LayerDrawMixin
from .mixins.layer_edit_mixin import LayerEditMixin
from .mixins.backup_mixin import BackupMixin
from .mixins.symbol_export_mixin import SymbolExportMixin
from .mixins.import_export_mixin import ImportExportMixin
from .mixins.report_mixin import ReportMixin


class RNADialog(
    QDialog, FORM_CLASS, ChartMixin, MapToolsMixin,
    AuthMixin, LayerOpsMixin, LayerDrawMixin, LayerEditMixin,
    BackupMixin, SymbolExportMixin, ImportExportMixin, ReportMixin,
):
    """Main dialog for the RNA QGIS plugin."""
    def __init__(self, iface, parent=None) -> None:
        """Constructor."""
        super(RNADialog, self).__init__(parent)
        self.iface = iface
        self._tr_locale = _load_locale()
        try:
            self.setupUi(self)
        except Exception as e:
            logger.exception("setupUi failed: %s", e)
            raise
        self._cache_originals()
        self._apply_translations()

        self.sat_view = None
        self.rast = None

        self.add_u.clicked.connect(lambda: self.public_route('add_usr'))
        self.submit_usr.clicked.connect(self.submit_add_usr)
        self.sign_in_user.clicked.connect(self.login_user)
        self.wilaya_list.currentIndexChanged.connect(self.on_select_wilaya)
        self.fill_map_options()
        fill_paper(self.paper)
        self.ln = None

        fill_wilayas_list(self.wilaya_list)

        self.cat_org.currentIndexChanged.connect(self.on_select_catOrg)

        self.cat_act.currentIndexChanged.connect(self.on_select_catAct)

        fill_road_type(self.type_voie)
        fill_numbering_state(self.num_etat)

        fill_mounting_status(self.etat_mont)

        self.abort_uc.clicked.connect(lambda: self.public_route('login'))
        fill_subdivision_type(self.type_city)
        fill_type_zone(self.type_zone)
        self.type_plan=""
        self.type_to_hide=""

        fill_road_reference(self.dyn_ref)
        fill_panel_reference(self.dyn_ref2)
        self.measure_tool=None
        self.measure_tool2=None

        self.dateEdit.setDate(QDate.currentDate())

        self.identify_tool = None
        self.identify_tool2 = None
        self.draw_road.clicked.connect(self.draw_road_handler)
        self.bc.clicked.connect(self.bon_commande)
        self.select_zone.clicked.connect(self.set_zone_selection)
        self.select_road.clicked.connect(self.set_road_selection)
        self.select_city.clicked.connect(self.set_city_selection)
        self.select_pan.clicked.connect(self.set_pan_selection)
        self.select_num.clicked.connect(self.set_num_selection)
        self.select_org.clicked.connect(self.set_org_selection)

        self.draw_org.clicked.connect(self.draw_org_handler)

        self.draw_pan.clicked.connect(self.draw_pan_handler)

        self.draw_city.clicked.connect(self.draw_city_handler)

        self.edit_road.clicked.connect(self.update_road)
        self.edit_org.clicked.connect(self.update_organization)
        self.edit_city.clicked.connect(self.update_city)
        self.edit_zone.clicked.connect(self.update_zone)
        self.edit_num.clicked.connect(self.update_numbering)
        self.edit_pan.clicked.connect(self.update_panel)

        self.popup_dialog = None
        self.menu.currentChanged.connect(self.on_opt_selected)

        self.submit_pan.clicked.connect(self.add_panel)
        self.submit_org.clicked.connect(self.add_organization)
        self.submit_num.clicked.connect(self.add_numbering)
        self.draw_num.clicked.connect(self.draw_num_handler)

        self.draw_zone.clicked.connect(self.draw_zone_handler)

        self.submit_voie.clicked.connect(self.add_road)

        self.print.clicked.connect(self.export_to_image1)
        self.mesure_dist.clicked.connect(self.measure_distance)

        self.submit_city.clicked.connect(self.add_city)
        self.submit_zone.clicked.connect(self.add_zone)
        self.logout_btn.clicked.connect(lambda: self.close())
        self.backup_db.clicked.connect(self.backup)
        self.list_voie.clicked.connect(self.list_roads)
        self.list_org.clicked.connect(self.list_organizations)
        self.list_cities.clicked.connect(self.list_subdivisions)
        self.list_num.clicked.connect(self.list_numberings)
        self.list_pan.clicked.connect(self.list_panels)
        self.select_ref.clicked.connect(self.select_ref_handler)
        self.select_ref2.clicked.connect(self.select_ref_handler2)

        self.report.clicked.connect(self.gen_report)

        self.restore_db.clicked.connect(self.restore_database)

        self.update_object = {}
        self.update_only_form = {}
        self.current_user=None
        self.iface.mapCanvas().setContextMenuPolicy(Qt.CustomContextMenu)

        self.iface.mapCanvas().customContextMenuRequested.connect(
            self.on_edition_release
        )
        self.iface.mapCanvas().mapToolSet.connect(self._on_map_tool_changed)

        self.pan.clicked.connect(self.carte_pano1)
        self.num_carte.clicked.connect(self.carte_num1)

        self.update_object = {}
        self.update_only_form = {}

        self.widget_2.keyPressEvent = lambda event: self.key_press_event(event)
        self.widget_4.keyPressEvent = lambda event: self.key_press_event2(event)

        self.mesure_dist_2.clicked.connect(self.measure_distance2)

        # --- Unified "Add New Type" in settings tab ---
        self.feature_combo.addItem("طريق", "road")
        self.feature_combo.addItem("منطقة", "zone")
        self.feature_combo.addItem("تجزئة", "subdivision")
        self.feature_combo.addItem("مرفق", "facility")
        self.feature_combo.addItem("نشاط", "activity")
        self.feature_combo.currentIndexChanged.connect(self._on_feature_changed)
        self.add_type_btn.clicked.connect(self._add_new_type)
        self._on_feature_changed(0)

        self._current_theme = DEFAULT_THEME
        self.setup_settings_ui()
        self._cache_originals()
        self._apply_translations()
        self.apply_theme()

    def _tr(self, source: str) -> str:
        return _i18n_tr(source, self._tr_locale)

    def setup_settings_ui(self) -> None:
        s = QSettings(SETTINGS_ORG, SETTINGS_APP)

        self._settings_group = QGroupBox(self._tr("الإعدادات"))
        self._settings_group.setObjectName("_settings_group")
        self._settings_group.setLayout(QVBoxLayout())

        # --- Theme ---
        theme_row = QHBoxLayout()
        self._theme_label = QLabel(self._tr("المظهر:"))
        self._theme_label.setObjectName("_theme_label")
        theme_row.addWidget(self._theme_label)
        self._theme_combo = QComboBox()
        self._theme_combo.addItem(THEME_DARK)
        self._theme_combo.addItem(THEME_LIGHT)
        self._theme_combo.currentTextChanged.connect(self._on_theme_changed)
        saved_theme = s.value(SETTINGS_KEY_THEME, DEFAULT_THEME)
        idx = self._theme_combo.findText(saved_theme)
        if idx >= 0:
            self._theme_combo.setCurrentIndex(idx)
        self._current_theme = self._theme_combo.currentText()
        theme_row.addWidget(self._theme_combo)
        self._settings_group.layout().addLayout(theme_row)

        # --- Locale ---
        locale_row = QHBoxLayout()
        self._locale_label = QLabel(self._tr("اللغة:"))
        self._locale_label.setObjectName("_locale_label")
        locale_row.addWidget(self._locale_label)
        self._locale_combo = QComboBox()
        for code, label in AVAILABLE_LOCALES:
            self._locale_combo.addItem(label, code)
        self._locale_combo.currentIndexChanged.connect(self._on_locale_changed)
        self._locale_combo.blockSignals(True)
        saved_locale = s.value(SETTINGS_KEY_LOCALE, "")
        if saved_locale:
            li = self._locale_combo.findData(saved_locale)
            if li >= 0:
                self._locale_combo.setCurrentIndex(li)
        self._locale_combo.blockSignals(False)
        locale_row.addWidget(self._locale_combo)
        self._settings_group.layout().addLayout(locale_row)

        self.scrollAreaWidgetContents_2.layout().addWidget(self._settings_group)

    def _cache_originals(self) -> None:
        for w in self.findChildren((QLabel, QPushButton, QCheckBox)):
            t = w.text()
            if t and any('\u0600' <= c <= '\u06FF' for c in t) and not w.property("_rna_src"):
                w.setProperty("_rna_src", t)
        for w in self.findChildren(QGroupBox):
            t = w.title()
            if t and any('\u0600' <= c <= '\u06FF' for c in t) and not w.property("_rna_src"):
                w.setProperty("_rna_src", t)
        for w in self.findChildren(QWidget):
            t = w.toolTip()
            if t and any('\u0600' <= c <= '\u06FF' for c in t) and not w.property("_rna_tip"):
                w.setProperty("_rna_tip", t)

    def _apply_translations(self) -> None:
        for w in self.findChildren((QLabel, QPushButton, QCheckBox)):
            try:
                s = w.property("_rna_src")
                if s:
                    w.setText(self._tr(s))
            except Exception as e:
                logger.warning("_tr %s: %s", w.objectName(), e)
        for w in self.findChildren(QGroupBox):
            try:
                s = w.property("_rna_src")
                if s:
                    w.setTitle(self._tr(s))
            except Exception as e:
                logger.warning("_tr %s: %s", w.objectName(), e)
        for w in self.findChildren(QWidget):
            try:
                s = w.property("_rna_tip")
                if s:
                    w.setToolTip(self._tr(s))
            except Exception as e:
                logger.warning("_tr %s: %s", w.objectName(), e)

    def _on_theme_changed(self, theme_name: str) -> None:
        self._current_theme = theme_name
        s = QSettings(SETTINGS_ORG, SETTINGS_APP)
        s.setValue(SETTINGS_KEY_THEME, theme_name)
        self.apply_theme()

    def _on_locale_changed(self, *args) -> None:
        code = self._locale_combo.currentData()
        if not code:
            return
        s = QSettings(SETTINGS_ORG, SETTINGS_APP)
        s.setValue(SETTINGS_KEY_LOCALE, code)
        self._tr_locale = code
        from .i18n import _cache
        _cache.clear()
        self._apply_translations()
        fill_road_type(self.type_voie)
        fill_type_zone(self.type_zone)
        fill_subdivision_type(self.type_city)
        fill_mounting_status(self.etat_mont)
        fill_numbering_state(self.num_etat)
        fill_paper(self.paper)

    def apply_theme(self) -> None:
        theme = self._current_theme
        qss = get_theme_qss(theme)
        self.setStyleSheet(qss)

    def _on_feature_changed(self, index: int) -> None:
        feature = self.feature_combo.itemData(index)
        has_subtype = feature in ("facility", "activity")
        self.label_subtype.setVisible(has_subtype)
        self.subtype_combo.setVisible(has_subtype)
        self.label_subsubtype.setVisible(has_subtype)
        self.subsubtype_combo.setVisible(has_subtype)
        if has_subtype:
            self.subtype_combo.clear()
            self.subsubtype_combo.clear()
            if feature == "facility":
                fill_org_category(self.subtype_combo)
            else:
                fill_activity_category(self.subtype_combo)

    def _add_new_type(self) -> None:
        feature = self.feature_combo.currentData()
        type_name = validate_text(self.new_type.text())
        has_subtype = feature in ("facility", "activity")
        subtype = self.subtype_combo.currentText() if has_subtype else ""
        subsubtype = self.subsubtype_combo.text() if has_subtype else ""

        if feature == "road":
            if type_name:
                add_road_type(type_name)
                self.new_type.clear()
                fill_road_type(self.type_voie)
        elif feature == "zone":
            if type_name:
                add_type_zone(type_name)
                self.new_type.clear()
                fill_type_zone(self.type_zone)
        elif feature == "subdivision":
            if type_name:
                add_subdivision_type(type_name)
                self.new_type.clear()
                fill_subdivision_type(self.type_city)
        elif feature == "facility":
            if type_name and subtype:
                add_organization_type(type_name, subtype, subsubtype)
                self.new_type.clear()
                fill_org_category(self.cat_org)
                fill_type_org(self.type_org, self.cat_org.itemData(0))
                fill_org_category(self.subtype_combo)
        elif feature == "activity":
            if type_name and subtype:
                add_activity_type(subtype, type_name, subsubtype)
                self.new_type.clear()
                fill_activity_category(self.cat_act)
                fill_type_act(self.type_act, self.cat_act.itemData(0))
                fill_activity_category(self.subtype_combo)
