"""
/***************************************************************************
 RNADialog
                                 A QGIS plugin
 RNA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-01-02
        git sha              : $Format:%H$
        copyright            : (C) 2025 by C.A.S
        email                : rna@qgis.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
from PyQt5.QtCore import Qt, QDate, QSettings
from PyQt5.QtWidgets import (
    QApplication, QCheckBox, QDialog, QGroupBox, QLabel,
    QPushButton, QVBoxLayout, QHBoxLayout, QComboBox, QWidget,
)
from qgis.PyQt import uic
from .gui.ui_fillers import (
    fill_wilayas_list, fill_paper, fill_road_type, fill_numbering_state,
    fill_mounting_status, fill_subdivision_type, fill_type_zone,
    fill_road_reference, fill_panel_reference, fill_org_category,
    fill_type_org, fill_activity_category, fill_type_act,
)

from .constants import (
    THEME_DARK, THEME_LIGHT, THEMES, DEFAULT_THEME,
    get_theme_qss, get_dialog_qss,
    SETTINGS_ORG, SETTINGS_APP, SETTINGS_KEY_THEME, SETTINGS_KEY_LOCALE,
    AVAILABLE_LOCALES,
)
from .scripts.lookup_data import get_string, apply_widget_texts, clear_i18n_cache
import logging
logger = logging.getLogger(__name__)


def _load_locale() -> str:
    s = QSettings(SETTINGS_ORG, SETTINGS_APP)
    locale = s.value(SETTINGS_KEY_LOCALE, '')
    if not locale:
        locale_val = QSettings().value('locale/userLocale')
        locale = locale_val[0:2] if locale_val else 'en'
    return locale

# This loads your .ui file so that PyQt can populate your plugin
# with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'gui', 'RNA_dialog_base.ui'))

from .mixins.chart_mixin import ChartMixin
from .mixins.map_tools_mixin import MapToolsMixin
from .mixins.auth_mixin import AuthMixin
from .mixins.layer_ops_mixin import LayerOpsMixin
from .mixins.layer_draw_mixin import LayerDrawMixin
from .mixins.layer_edit_mixin import LayerEditMixin
from .mixins.backup_mixin import BackupMixin
from .mixins.symbol_export_mixin import SymbolExportMixin
from .mixins.import_export_mixin import ImportExportMixin
from .mixins.report_mixin import ReportMixin


class RNADialog(
    QDialog, FORM_CLASS, ChartMixin, MapToolsMixin,
    AuthMixin, LayerOpsMixin, LayerDrawMixin, LayerEditMixin,
    BackupMixin, SymbolExportMixin, ImportExportMixin, ReportMixin,
):
    """Main dialog for the RNA QGIS plugin."""
    def __init__(self, iface, parent=None) -> None:
        """Constructor."""
        super(RNADialog, self).__init__(parent)
        self.iface = iface
        self._tr_locale = _load_locale()
        if self._tr_locale == 'ar':
            QApplication.setLayoutDirection(Qt.RightToLeft)
        else:
            QApplication.setLayoutDirection(Qt.LeftToRight)
        try:
            self.setupUi(self)
        except Exception as e:
            logger.exception("setupUi failed: %s", e)
            raise
        self.sat_view = None
        self.rast = None

        self.add_u.clicked.connect(lambda: self.public_route('add_usr'))
        self.submit_usr.clicked.connect(self.submit_add_usr)
        self.sign_in_user.clicked.connect(self.login_user)
        self.wilaya_list.currentIndexChanged.connect(self.on_select_wilaya)
        self.fill_map_options()
        fill_paper(self.paper)
        self.ln = None

        fill_wilayas_list(self.wilaya_list)

        self.cat_org.currentIndexChanged.connect(self.on_select_catOrg)

        self.cat_act.currentIndexChanged.connect(self.on_select_catAct)

        fill_road_type(self.type_voie)
        fill_numbering_state(self.num_etat)

        fill_mounting_status(self.etat_mont)

        self.abort_uc.clicked.connect(lambda: self.public_route('login'))
        fill_subdivision_type(self.type_city)
        fill_type_zone(self.type_zone)
        self.type_plan=""
        self.type_to_hide=""

        fill_road_reference(self.dyn_ref)
        fill_panel_reference(self.dyn_ref2)
        self.measure_tool=None
        self.measure_tool2=None

        self.dateEdit.setDate(QDate.currentDate())

        self.identify_tool = None
        self.identify_tool2 = None
        self.draw_road.clicked.connect(self.draw_road_handler)
        self.bc.clicked.connect(self.bon_commande)
        self.select_zone.clicked.connect(self.set_zone_selection)
        self.select_road.clicked.connect(self.set_road_selection)
        self.select_city.clicked.connect(self.set_city_selection)
        self.select_pan.clicked.connect(self.set_pan_selection)
        self.select_num.clicked.connect(self.set_num_selection)
        self.select_org.clicked.connect(self.set_org_selection)

        self.draw_org.clicked.connect(self.draw_org_handler)

        self.draw_pan.clicked.connect(self.draw_pan_handler)

        self.draw_city.clicked.connect(self.draw_city_handler)

        self.edit_road.clicked.connect(self.update_road)
        self.edit_org.clicked.connect(self.update_organization)
        self.edit_city.clicked.connect(self.update_city)
        self.edit_zone.clicked.connect(self.update_zone)
        self.edit_num.clicked.connect(self.update_numbering)
        self.edit_pan.clicked.connect(self.update_panel)

        self.popup_dialog = None
        self.menu.currentChanged.connect(self.on_opt_selected)

        self.submit_pan.clicked.connect(self.add_panel)
        self.submit_org.clicked.connect(self.add_organization)
        self.submit_num.clicked.connect(self.add_numbering)
        self.draw_num.clicked.connect(self.draw_num_handler)

        self.draw_zone.clicked.connect(self.draw_zone_handler)

        self.submit_voie.clicked.connect(self.add_road)

        self.print.clicked.connect(self.export_to_image1)
        self.mesure_dist.clicked.connect(self.measure_distance)

        self.submit_city.clicked.connect(self.add_city)
        self.submit_zone.clicked.connect(self.add_zone)
        self.logout_btn.clicked.connect(lambda: self.close())
        self.backup_db.clicked.connect(self.backup)
        self.list_voie.clicked.connect(self.list_roads)
        self.list_org.clicked.connect(self.list_organizations)
        self.list_cities.clicked.connect(self.list_subdivisions)
        self.list_num.clicked.connect(self.list_numberings)
        self.list_pan.clicked.connect(self.list_panels)
        self.select_ref.clicked.connect(self.select_ref_handler)
        self.select_ref2.clicked.connect(self.select_ref_handler2)

        self.report.clicked.connect(self.gen_report)

        self.restore_db.clicked.connect(self.restore_database)

        self.update_object = {}
        self.update_only_form = {}
        self.current_user=None
        self.iface.mapCanvas().setContextMenuPolicy(Qt.CustomContextMenu)

        self.iface.mapCanvas().customContextMenuRequested.connect(
            self.on_edition_release
        )
        self.iface.mapCanvas().mapToolSet.connect(self._on_map_tool_changed)

        self.pan.clicked.connect(self.carte_pano1)
        self.num_carte.clicked.connect(self.carte_num1)

        self.update_object = {}
        self.update_only_form = {}

        self.widget_2.keyPressEvent = lambda event: self.key_press_event(event)
        self.widget_4.keyPressEvent = lambda event: self.key_press_event2(event)

        self.mesure_dist_2.clicked.connect(self.measure_distance2)

        self._current_theme = DEFAULT_THEME
        self.setup_settings_ui()
        apply_widget_texts(self, self._tr_locale)
        self.apply_theme()

    def _tr(self, source: str) -> str:
        return get_string(source, self._tr_locale)

    def setup_settings_ui(self) -> None:
        s = QSettings(SETTINGS_ORG, SETTINGS_APP)

        self._settings_group = QGroupBox(get_string("الإعدادات", self._tr_locale))
        self._settings_group.setObjectName("_settings_group")
        self._settings_group.setLayout(QVBoxLayout())

        theme_row = QHBoxLayout()
        self._theme_label = QLabel(get_string("المظهر:", self._tr_locale))
        self._theme_label.setObjectName("_theme_label")
        theme_row.addWidget(self._theme_label)
        self._theme_combo = QComboBox()
        self._theme_combo.addItem(THEME_DARK)
        self._theme_combo.addItem(THEME_LIGHT)
        self._theme_combo.currentTextChanged.connect(self._on_theme_changed)
        saved_theme = s.value(SETTINGS_KEY_THEME, DEFAULT_THEME)
        idx = self._theme_combo.findText(saved_theme)
        if idx >= 0:
            self._theme_combo.setCurrentIndex(idx)
        self._current_theme = self._theme_combo.currentText()
        theme_row.addWidget(self._theme_combo)
        self._settings_group.layout().addLayout(theme_row)

        locale_row = QHBoxLayout()
        self._locale_label = QLabel(get_string("اللغة:", self._tr_locale))
        self._locale_label.setObjectName("_locale_label")
        locale_row.addWidget(self._locale_label)
        self._locale_combo = QComboBox()
        for code, label in AVAILABLE_LOCALES:
            self._locale_combo.addItem(label, code)
        self._locale_combo.currentIndexChanged[int].connect(self._on_locale_changed)
        self._locale_combo.blockSignals(True)
        saved_locale = s.value(SETTINGS_KEY_LOCALE, "")
        if saved_locale:
            li = self._locale_combo.findData(saved_locale)
            if li >= 0:
                self._locale_combo.setCurrentIndex(li)
        self._locale_combo.blockSignals(False)
        locale_row.addWidget(self._locale_combo)
        self._settings_group.layout().addLayout(locale_row)

        self.scrollAreaWidgetContents_2.layout().addWidget(self._settings_group)

    def _on_theme_changed(self, theme_name: str) -> None:
        self._current_theme = theme_name
        s = QSettings(SETTINGS_ORG, SETTINGS_APP)
        s.setValue(SETTINGS_KEY_THEME, theme_name)
        self.apply_theme()

    def _on_locale_changed(self, idx: int) -> None:
        code = self._locale_combo.currentData()
        if not code:
            return
        s = QSettings(SETTINGS_ORG, SETTINGS_APP)
        s.setValue(SETTINGS_KEY_LOCALE, code)
        self._tr_locale = code
        clear_i18n_cache()
        apply_widget_texts(self, code)
        fill_wilayas_list(self.wilaya_list)
        fill_road_type(self.type_voie)
        fill_type_zone(self.type_zone)
        fill_subdivision_type(self.type_city)
        fill_mounting_status(self.etat_mont)
        fill_numbering_state(self.num_etat)
        fill_paper(self.paper)
        fill_org_category(self.cat_org)
        fill_activity_category(self.cat_act)
        if code == 'ar':
            QApplication.setLayoutDirection(Qt.RightToLeft)
        else:
            QApplication.setLayoutDirection(Qt.LeftToRight)

    def apply_theme(self) -> None:
        theme = self._current_theme
        qss = get_theme_qss(theme)
        self.setStyleSheet(qss)


