"""
/***************************************************************************
 MainDialog
                                   A QGIS plugin
 RNA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                                -------------------
         begin                : 2025-01-02
         git sha              : $Format:%H$
         copyright            : (C) 2025 by C.A.S
         email                : rna@qgis.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import logging
import os
from typing import Any

from qgis.PyQt.QtCore import QObject, QSettings, Qt, QUrl, pyqtSlot
from qgis.PyQt.QtWidgets import QApplication, QDialog, QFileDialog, QVBoxLayout

try:
    from qgis.PyQt.QtQuickWidgets import QQuickWidget

    _HAS_QML = True
except ImportError:
    QQuickWidget = None
    _HAS_QML = False

from ..constants import (
    AVAILABLE_LOCALES,
    DEFAULT_THEME,
    SETTINGS_APP,
    SETTINGS_KEY_LOCALE,
    SETTINGS_KEY_THEME,
    SETTINGS_ORG,
    THEME_DARK,
    THEME_LIGHT,
    current_locale,
    get_theme_qss,
)
from ..gui.identify_tool import IdentifyTool
from ..gui.measure_tool import MeasureTool
from ..gui.popup_dialog import PopupDialog
from ..mixins.auth_mixin import AuthMixin
from ..mixins.backup_mixin import BackupMixin
from ..mixins.chart_mixin import ChartMixin
from ..mixins.import_export_mixin import ImportExportMixin
from ..mixins.layer_draw_mixin import LayerDrawMixin
from ..mixins.layer_edit_mixin import LayerEditMixin
from ..mixins.layer_ops_mixin import LayerOpsMixin
from ..mixins.map_tools_mixin import MapToolsMixin
from ..mixins.report_mixin import ReportMixin
from ..mixins.symbol_export_mixin import SymbolExportMixin
from ..scripts.lookup_data import (
    apply_widget_texts,
    clear_i18n_cache,
    get_string,
)
from .proxies import (
    _COMBO_NAMES,
    _FIELD_NAMES,
    _ComboProxy,
    _FieldProxy,
    _FormStackProxy,
    _MenuProxy,
    _RouterProxy,
)
from .ui_fillers import (
    _ACTIVITY_KEY,
    fill_activity_category,
    fill_feature_combo,
    fill_mounting_status,
    fill_numbering_state,
    fill_org_category,
    fill_panel_reference,
    fill_paper,
    fill_road_reference,
    fill_road_type,
    fill_subdivision_type,
    fill_subtype_combo,
    fill_wilayas_list,
    fill_zone_type,
    save_new_type,
)

logger = logging.getLogger(__name__)

PLUGIN_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
QML_DIR = os.path.join(PLUGIN_DIR, 'qml')


class MainDialogBridge(QObject):
    """Bridge object exposed to QML for Python <-> QML communication."""

    def __init__(self, dialog: 'MainDialog') -> None:
        super().__init__()
        self.dialog = dialog

    def _pull_fields(self) -> None:
        root = self._qml_root()
        if not root:
            return
        for name, proxy in self.dialog._field_proxies.items():
            qml_text = str(root.getFieldText(name))
            proxy._text = qml_text

    @pyqtSlot(str)
    def onPageSubmit(self, pageName: str) -> None:
        d = self.dialog
        self._pull_fields()
        dispatch = {
            'login': d.login_user,
            'add_usr': d.submit_add_usr,
            'restore_db': d.restore_database,
            'zone': d.add_zone,
            'road': d.add_road,
            'org': d.add_organization,
            'city': d.add_city,
            'num': d.add_numbering,
            'pan': d.add_panel,
            'toggle_settings': d._toggle_settings,
            'draw': d.start_drawing,
            'select': d.start_selecting,
            'edit': d.start_editing,
            'measure': d.activate_measure,
            'save_action': d._on_save_action,
            'save_new_type': d._save_new_type,
            'list_roads': d.list_road_entries,
            'list_orgs': d.list_organizations,
            'list_subds': d.list_subdivisions,
            'list_nums': d.list_numberings,
            'list_panels': d.list_panel_signs,
        }
        handler = dispatch.get(pageName)
        if handler:
            handler()

    @pyqtSlot(str, int, str)
    def onComboChanged(self, objectName: str, index: int, currentData: str) -> None:
        d = self.dialog
        if objectName == 'wilaya_list':
            d.on_select_wilaya(index)
        elif objectName == 'org_cat':
            d.on_select_org_cat(index)
        elif objectName == 'activity_cat':
            d.on_select_activity_cat(index)
        elif objectName == 'layer_selector':
            d._on_layer_changed(index)
        elif objectName == 'feature_combo':
            d._on_feature_changed(index)
        elif objectName == 'map_options':
            proxy = d._combo_proxies.get('map_options')
            if proxy:
                proxy.setCurrentIndex(index)
                logger.info(
                    'onComboChanged map_options: index=%d, text=%s, data=%s',
                    index,
                    proxy.currentText(),
                    proxy.currentData(),
                )
        elif objectName == '_action_combo':
            d._on_action_changed(index)
        elif objectName == 'menu':
            d.on_opt_selected(index)
        elif objectName == '_theme_combo':
            d._on_theme_changed(index)
        elif objectName == '_locale_combo':
            d._on_locale_changed(index)

    @pyqtSlot(str, str)
    def onSelectRef(self, objectName: str, layerName: str) -> None:
        d = self.dialog
        if objectName == 'road_ref':
            d.select_ref_handler()
        elif objectName == 'panel_ref':
            d.select_panel_ref_handler()

    def _qml_root(self):
        try:
            return self.dialog._quick_widget.rootObject()
        except Exception:
            return None

    def _switch_page(self, page_name: str) -> None:
        root = self._qml_root()
        if root:
            root.switchPage(page_name)

    def _set_tab_index(self, index: int) -> None:
        root = self._qml_root()
        if root:
            root.setSettingsTabIndex(index)

    def _get_tab_index(self) -> int:
        return 0

    def _set_form_stack_index(self, index: int) -> None:
        root = self._qml_root()
        if root:
            root.setFormStackIndex(index)

    def _get_form_stack_index(self) -> int:
        return 0

    def _push_combos(self) -> None:
        for name in self.dialog._combo_proxies:
            self._push_combo(name)

    def _push_combo(self, name: str) -> None:
        """Push locally stored combo data to QML."""
        proxy = self.dialog._combo_proxies.get(name)
        if not proxy:
            return
        items = [
            {'text': str(v.get('text', '')), 'value': str(v.get('value', ''))}
            for v in proxy._items
        ]
        logger.info(
            '_push_combo %s: %d items, proxy._index=%d', name, len(items), proxy._index
        )
        root = self._qml_root()
        if root:
            root.setComboOptions(name, items)

    def _push_field(self, name: str) -> None:
        proxy = self.dialog._field_proxies.get(name)
        if not proxy:
            return
        root = self._qml_root()
        if root:
            root.setFieldText(name, proxy._text)


class MainDialog(
    QDialog,
    ChartMixin,
    MapToolsMixin,
    AuthMixin,
    LayerOpsMixin,
    LayerDrawMixin,
    LayerEditMixin,
    BackupMixin,
    SymbolExportMixin,
    ImportExportMixin,
    ReportMixin,
):
    """Main dialog for the RNA QGIS plugin — QML-backed."""

    def __init__(self, iface, parent=None) -> None:
        super().__init__(parent)
        self.iface = iface
        self._tr_locale = current_locale()
        if self._tr_locale == 'ar':
            QApplication.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        else:
            QApplication.setLayoutDirection(Qt.LayoutDirection.LeftToRight)

        self._bridge = MainDialogBridge(self)
        self._init_proxies()
        self._current_theme = DEFAULT_THEME
        self._init_qml()

        self._init_state()
        self._connect_bridge_signals()
        self._populate_combos()
        self.fill_map_options()
        mo = self._combo_proxies.get('map_options')
        if mo:
            logger.info(
                'map_options after fill: items=%d, index=%d, first_item=%s',
                len(mo._items),
                mo._index,
                mo._items[0] if mo._items else 'NONE',
            )
        self._bridge._push_combos()

        self.iface.mapCanvas().setContextMenuPolicy(
            Qt.ContextMenuPolicy.CustomContextMenu
        )
        self.iface.mapCanvas().customContextMenuRequested.connect(
            self.on_edition_release
        )
        self.iface.mapCanvas().mapToolSet.connect(self._on_map_tool_changed)

        self._init_theme_locale()
        self._bridge._push_combos()
        apply_widget_texts(self, self._tr_locale)
        self._translate_internal_combos()
        self._bridge._push_combos()
        self.apply_theme()

    # ------------------------------------------------------------------
    # Proxy & bridge setup
    # ------------------------------------------------------------------
    def _init_proxies(self) -> None:
        self._combo_proxies: dict[str, _ComboProxy] = {}
        for name in _COMBO_NAMES:
            self._combo_proxies[name] = _ComboProxy()

        self._field_proxies: dict[str, _FieldProxy] = {}
        for name in _FIELD_NAMES:
            self._field_proxies[name] = _FieldProxy()

        self.router = _RouterProxy(self._bridge)
        self.menu = _MenuProxy(self._bridge)
        self.form_stack = _FormStackProxy(self._bridge)

    def _init_qml(self) -> None:  # pylint: disable=duplicate-code
        if not _HAS_QML or QQuickWidget is None:
            raise ImportError(
                'Qt Quick Widgets (QtQml) is not available.\n'
                'Please install the Qt Quick / QML package for your system\n'
                '(e.g., python3-pyqt6.qml or qml6 on Debian/Ubuntu).'
            )
        self.setObjectName('rnaMainDialog')
        self.setMinimumSize(640, 680)
        self.resize(680, 720)
        self.setSizeGripEnabled(True)

        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        self._quick_widget = QQuickWidget()
        self._quick_widget.setResizeMode(QQuickWidget.SizeRootObjectToView)

        engine = self._quick_widget.engine()
        engine.addImportPath(QML_DIR)
        for p in (
            '/usr/lib64/qt5/qml',
            '/usr/lib/qt5/qml',
        ):
            if os.path.isdir(p):
                engine.addImportPath(p)

        context = self._quick_widget.rootContext()
        context.setContextProperty('pluginBridge', self._bridge)
        context.setContextProperty('isDark', self._current_theme == 'dark')
        context.setContextProperty('isRTL', self._tr_locale == 'ar')

        qml_path = os.path.join(QML_DIR, 'maindialog', 'MainDialog.qml')
        self._quick_widget.setSource(QUrl.fromLocalFile(qml_path))

        layout.addWidget(self._quick_widget)

    def _connect_bridge_signals(self) -> None:
        root = self._quick_widget.rootObject()
        if root is None:
            raise RuntimeError(
                'QML root object is None — check QML syntax and imports.'
            )
        root.submitForm.connect(self._bridge.onPageSubmit)
        root.comboChanged.connect(self._bridge.onComboChanged)
        root.selectRef.connect(self._bridge.onSelectRef)

    # ------------------------------------------------------------------
    # Widget attribute access (compat for mixins)
    # ------------------------------------------------------------------
    def __getattr__(self, name: str):
        if name in _COMBO_NAMES:
            return self._combo_proxies.get(name)
        if name in _FIELD_NAMES:
            return self._field_proxies.get(name)
        raise AttributeError(
            f"'{type(self).__name__}' object has no attribute '{name}'"
        )

    # ------------------------------------------------------------------
    # State
    # ------------------------------------------------------------------
    def _init_state(self) -> None:
        self.sat_view: str | None = None
        self.rast: str | None = None
        self.ln: str | None = None
        self.type_plan: str = ''
        self.type_to_hide: str = ''
        self.measure_tool: MeasureTool | None = None
        self.identify_tool: IdentifyTool | None = None
        self.ref_identify_tool: IdentifyTool | None = None
        self.popup_dialog: PopupDialog | None = None
        self.current_user: dict[str, Any] | None = None
        self._output_dir: str = os.path.expanduser('~/Documents')
        self.update_object: dict[str, Any] = {}
        self.update_only_form: dict[str, Any] = {}

    # ------------------------------------------------------------------
    # Toggle settings
    # ------------------------------------------------------------------
    def _toggle_settings(self) -> None:
        root = self._bridge._qml_root()
        if root:
            root.toggleSettingsTab()

    # ------------------------------------------------------------------
    # Action combo (Maps, Reports and Backup section)
    # ------------------------------------------------------------------
    def _on_action_changed(self, _index: int) -> None:
        action_proxy = self._combo_proxies.get('_action_combo')
        action = action_proxy.currentData() if action_proxy else None
        paper_proxy = self._combo_proxies.get('paper')
        is_map = action in ('panels_map', 'num_map')
        if paper_proxy:
            paper_proxy.setVisible(is_map)
        if action == 'panels_map':
            self.panel_chart()
        elif action == 'num_map':
            self.numbering_chart()

    def _on_save_action(self) -> None:
        directory = QFileDialog.getExistingDirectory(
            self,
            self._tr('Choose output directory'),
            self._output_dir,
        )
        if not directory:
            return
        self._output_dir = directory
        action_proxy = self._combo_proxies.get('_action_combo')
        action = action_proxy.currentData() if action_proxy else None
        if action == 'report':
            self.generate_report()
        elif action == 'order':
            self.purchase_order()
        elif action == 'panels_map':
            self.panel_chart()
            self.export_to_image()
        elif action == 'num_map':
            self.numbering_chart()
            self.export_to_image()
        elif action == 'backup':
            self.backup()

    # ------------------------------------------------------------------
    # Feature / type management
    # ------------------------------------------------------------------
    def _on_feature_changed(self, index: int) -> None:
        feature_combo = self._combo_proxies.get('feature_combo')
        if not feature_combo:
            return
        main_type = feature_combo.itemData(index)
        if not isinstance(main_type, str):
            return
        is_activity = main_type == _ACTIVITY_KEY
        label_subtype = self._field_proxies.get('label_subtype')
        new_type = self._field_proxies.get('new_type')
        if label_subtype:
            label_subtype.setVisible(is_activity)
        if new_type:
            new_type.setVisible(is_activity)
        subtype_combo = self._combo_proxies.get('subtype_combo')
        if subtype_combo:
            fill_subtype_combo(subtype_combo, main_type)

    def _save_new_type(self) -> None:
        feature_combo = self._combo_proxies.get('feature_combo')
        if not feature_combo:
            return
        index = feature_combo.currentIndex()
        main_type = feature_combo.itemData(index)
        new_type_proxy = self._field_proxies.get('new_type')
        type_name = new_type_proxy.text().strip() if new_type_proxy else ''
        subtype_combo = self._combo_proxies.get('subtype_combo')
        if not type_name and subtype_combo:
            type_name = subtype_combo.currentText().strip()
        category = (
            subtype_combo.currentData()
            if subtype_combo and main_type == _ACTIVITY_KEY
            else ''
        )
        if save_new_type(main_type, type_name, category):
            if new_type_proxy:
                new_type_proxy.clear()
            if subtype_combo:
                fill_subtype_combo(subtype_combo, main_type)
                clear_i18n_cache()
                count = subtype_combo.count()
                if count > 0:
                    subtype_combo.setCurrentIndex(count - 1)

    # ------------------------------------------------------------------
    # Layer / form stack
    # ------------------------------------------------------------------
    def _on_layer_changed(self, index: int) -> None:
        self.form_stack.setCurrentIndex(index)
        proxy = self._combo_proxies.get('layer_selector')
        if proxy:
            proxy.setCurrentIndex(index)
        widget = (
            self.menu.currentWidget() if hasattr(self.menu, 'currentWidget') else None
        )
        if widget is not None and widget.objectName() == 'tab_ops':
            self.on_opt_selected(self.menu.currentIndex())

    LAYER_INDEX_MAP = [
        'Zones',
        'Roads',
        'Facilities',
        'Subdivisions',
        'Numbering',
        'Panels',
    ]

    def _current_layer_name(self) -> str:
        layer_selector = self._combo_proxies.get('layer_selector')
        idx = layer_selector.currentIndex() if layer_selector else 0
        if 0 <= idx < len(self.LAYER_INDEX_MAP):
            return self.LAYER_INDEX_MAP[idx]
        return self.LAYER_INDEX_MAP[0]

    # ------------------------------------------------------------------
    # Combo population
    # ------------------------------------------------------------------
    def _populate_combos(self) -> None:
        layer_selector = self._combo_proxies.get('layer_selector')
        if layer_selector:
            for name in self.LAYER_INDEX_MAP:
                layer_selector.addItem(name, name)
        fill_paper(self._combo_proxies.get('paper'))
        fill_wilayas_list(self._combo_proxies.get('wilaya_list'))
        fill_road_type(self._combo_proxies.get('type_road'))
        fill_numbering_state(self._combo_proxies.get('num_state'))
        fill_mounting_status(self._combo_proxies.get('mount_status'))
        fill_subdivision_type(self._combo_proxies.get('subd_type'))
        fill_zone_type(self._combo_proxies.get('zone_type'))
        fill_road_reference(self._combo_proxies.get('road_ref'))
        fill_panel_reference(self._combo_proxies.get('panel_ref'))
        fill_feature_combo(self._combo_proxies.get('feature_combo'))
        self._on_feature_changed(self._combo_proxies['feature_combo'].currentIndex())

    # ------------------------------------------------------------------
    # Translation helpers
    # ------------------------------------------------------------------
    def _tr(self, source: str) -> str:
        return get_string(source, self._tr_locale)

    def _translate_internal_combos(self) -> None:
        loc = self._tr_locale
        layer_selector = self._combo_proxies.get('layer_selector')
        if layer_selector:
            for i, name in enumerate(self.LAYER_INDEX_MAP):
                layer_selector.setItemText(i, get_string(name, loc))
        theme_combo = self._combo_proxies.get('_theme_combo')
        if theme_combo:
            for i in range(theme_combo.count()):
                theme_value = theme_combo.itemData(i)
                theme_combo.setItemText(i, get_string(theme_value, loc))

    # ------------------------------------------------------------------
    # Theme / locale
    # ------------------------------------------------------------------
    def _init_theme_locale(self) -> None:
        settings = QSettings(SETTINGS_ORG, SETTINGS_APP)
        theme_combo = self._combo_proxies.get('_theme_combo')
        if theme_combo:
            theme_combo.addItem(THEME_DARK, THEME_DARK)
            theme_combo.addItem(THEME_LIGHT, THEME_LIGHT)
            saved_theme = settings.value(SETTINGS_KEY_THEME, DEFAULT_THEME)
            theme_map = {'فاتح': THEME_LIGHT, 'داكن': THEME_DARK}
            saved_theme = theme_map.get(saved_theme, saved_theme)
            try:
                idx = theme_combo.findData(saved_theme)
            except (ValueError, TypeError):
                idx = -1
            if idx >= 0:
                theme_combo.setCurrentIndex(idx)
                settings.setValue(SETTINGS_KEY_THEME, saved_theme)
            self._current_theme = theme_combo.currentData()
        locale_combo = self._combo_proxies.get('_locale_combo')
        if locale_combo:
            for code, label in AVAILABLE_LOCALES:
                locale_combo.addItem(label, code)
            saved_locale = settings.value(SETTINGS_KEY_LOCALE, '')
            if saved_locale:
                li = locale_combo.findData(saved_locale)
                if li >= 0:
                    locale_combo.setCurrentIndex(li)

    def _on_theme_changed(self, _index: int) -> None:
        theme_combo = self._combo_proxies.get('_theme_combo')
        if theme_combo:
            self._current_theme = theme_combo.currentData()
        settings = QSettings(SETTINGS_ORG, SETTINGS_APP)
        settings.setValue(SETTINGS_KEY_THEME, self._current_theme)
        self.apply_theme()

    def _on_locale_changed(self, _idx: int) -> None:
        locale_combo = self._combo_proxies.get('_locale_combo')
        if not locale_combo:
            return
        code = locale_combo.currentData()
        if not code:
            return
        settings = QSettings(SETTINGS_ORG, SETTINGS_APP)
        settings.setValue(SETTINGS_KEY_LOCALE, code)
        self._tr_locale = code
        clear_i18n_cache()
        apply_widget_texts(self, code)
        self._translate_internal_combos()
        fill_wilayas_list(self._combo_proxies.get('wilaya_list'))
        fill_road_type(self._combo_proxies.get('type_road'))
        fill_zone_type(self._combo_proxies.get('zone_type'))
        fill_subdivision_type(self._combo_proxies.get('subd_type'))
        fill_mounting_status(self._combo_proxies.get('mount_status'))
        fill_numbering_state(self._combo_proxies.get('num_state'))
        fill_road_reference(self._combo_proxies.get('road_ref'))
        fill_panel_reference(self._combo_proxies.get('panel_ref'))
        fill_paper(self._combo_proxies.get('paper'))
        fill_org_category(self._combo_proxies.get('org_cat'))
        fill_activity_category(self._combo_proxies.get('activity_cat'))
        if code == 'ar':
            QApplication.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        else:
            QApplication.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        try:
            root = self._quick_widget.rootObject()
            if root:
                root.updateLayoutDirection(code == 'ar')
        except Exception:
            pass

    def apply_theme(self) -> None:
        theme = self._current_theme
        qss = get_theme_qss(theme)
        self.setStyleSheet(qss)
        is_dark = theme == 'dark'
        try:
            root = self._quick_widget.rootObject()
            if root:
                root.updateTheme(is_dark)
        except Exception:
            pass
