"""
/***************************************************************************
 MainDialog
                                   A QGIS plugin
 CAM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                                  -------------------
         begin                : 2025-01-02
         git sha              : $Format:%H$
copyright            : (C) 2025 by Zuhir Benslama
email                : zuhirbenslama@protonmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 3 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import logging
from collections.abc import Callable
from enum import Enum
from typing import Any, ClassVar

from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtWidgets import (
    QApplication,
    QDialog,
    QMessageBox,
    QStackedWidget,
    QVBoxLayout,
)

from ..constants import DEFAULT_THEME, current_locale
from ..gui.identify_tool import IdentifyTool
from ..gui.measure_tool import MeasureTool
from ..gui.popup_dialog import PopupDialog
from ..mixins.auth_mixin import AuthMixin
from ..mixins.backup_mixin import BackupMixin
from ..mixins.chart_mixin import ChartMixin
from ..mixins.import_export_mixin import ImportExportMixin
from ..mixins.layer_draw_mixin import LayerDrawMixin
from ..mixins.layer_edit_mixin import LayerEditMixin
from ..mixins.layer_ops_mixin import LayerOpsMixin
from ..mixins.map_tools_mixin import MapToolsMixin
from ..mixins.report_mixin import ReportMixin
from ..mixins.symbol_export_mixin import SymbolExportMixin
from ..scripts.widget_texts import (
    apply_widget_texts,
    clear_i18n_cache,
    get_string,
    widget_text,
)
from .dialog_helpers import _TabWidget
from .dialog_state import (
    apply_theme as state_apply_theme,
)
from .dialog_state import (
    init_theme_locale,
    on_action_changed,
    on_locale_changed,
    on_save_action,
    on_theme_changed,
    populate_combos,
    translate_internal_combos,
)
from .pages.add_user_page import build_add_user_page
from .pages.login_page import build_login_page
from .pages.main_page import build_main_page
from .ui_fillers import (
    ACTIVITY_KEY,
    fill_subtype_combo,
)
from .ui_fillers import (
    save_new_type as save_new_type_to_json,
)

logger = logging.getLogger(__name__)


class Action(Enum):
    """Typed action names for the _on_submit dispatch table."""

    LOGIN = 'login'
    ADD_USR = 'add_usr'
    RESTORE_DB = 'restore_db'
    ZONE = 'zone'
    ROAD = 'road'
    ORG = 'org'
    CITY = 'city'
    NUM = 'num'
    PAN = 'pan'
    DRAW = 'draw'
    SELECT = 'select'
    MEASURE = 'measure'
    SAVE_ACTION = 'save_action'
    SAVE_NEW_TYPE = 'save_new_type'
    LIST_ROADS = 'list_roads'
    LIST_ORGS = 'list_orgs'
    LIST_SUBDS = 'list_subds'
    LIST_NUMS = 'list_nums'
    LIST_PANELS = 'list_panels'
    EDIT = 'edit'


# Dispatch table for _on_submit — maps action names to 0-argument handlers.
_SUBMIT_DISPATCH: dict[Action, Callable[[], None]] = {}


def _run_init_steps(steps: list[tuple[str, Callable[..., Any]]]) -> None:
    """Execute a list of ``(name, callable)`` init steps, logging failures."""
    for name, fn in steps:
        try:
            fn()
        except Exception:
            logger.exception('Init step %r failed', name)
            raise


class MainDialog(
    QDialog,
    ChartMixin,
    MapToolsMixin,
    AuthMixin,
    LayerOpsMixin,
    LayerDrawMixin,
    LayerEditMixin,
    BackupMixin,
    SymbolExportMixin,
    ImportExportMixin,
    ReportMixin,
):
    """Main dialog for the CAM QGIS plugin — Qt Widgets version.

    UI logic is split across the following mixins:
    - AuthMixin: login/sign-up/logout flows.
    - ChartMixin: panel and numbering distribution charts.
    - LayerOpsMixin: layer tabs, feature CRUD, geometry validation.
    - LayerDrawMixin: drawing/editing sessions on map layers.
    - LayerEditMixin: feature add/edit via forms.
    - MapToolsMixin: measure/identify/select map tools.
    - BackupMixin: SQLite/SpatiaLite backup and restore.
    - ImportExportMixin: PNG map export / external export scripts.
    - SymbolExportMixin: SVG/PNG layout exports (legend, scale bar...).
    - ReportMixin: statistical reports and purchase orders.
    """

    def __init__(self, iface, parent=None) -> None:
        super().__init__(parent)
        self.iface = iface
        self._tr_locale = current_locale()
        if self._tr_locale == 'ar':
            QApplication.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        else:
            QApplication.setLayoutDirection(Qt.LayoutDirection.LeftToRight)

        self._current_theme = DEFAULT_THEME
        self._settings_visible = False

        _run_init_steps(
            [
                ('_init_ui', self._init_ui),
                ('_populate_dispatch', self._populate_dispatch),
                ('_init_state', self._init_state),
                ('init_theme_locale', lambda: init_theme_locale(self)),
                ('populate_combos', lambda: populate_combos(self)),
                ('fill_map_options', self.fill_map_options),
                ('_connect_signals', self._connect_signals),
                ('map canvas setup', self._setup_map_canvas),
                (
                    'apply_widget_texts',
                    lambda: apply_widget_texts(self, self._tr_locale),
                ),
                ('translate_internal_combos', self._setup_i18n),
                ('apply_theme', self.apply_theme),
            ]
        )

    # ------------------------------------------------------------------
    # UI Construction
    # ------------------------------------------------------------------

    def _init_ui(self) -> None:
        self.setObjectName('rnaMainDialog')
        self.setMinimumSize(360, 680)
        self.resize(360, 720)
        self.setSizeGripEnabled(True)

        main_layout = QVBoxLayout(self)
        main_layout.setContentsMargins(0, 0, 0, 0)

        self._held_widgets: list[Any] = []

        self._page_stack = QStackedWidget()
        main_layout.addWidget(self._page_stack)

        build_login_page(self)
        build_add_user_page(self)
        build_main_page(self)

        self._page_stack.setCurrentIndex(0)

        self.router = self._page_stack
        self.menu = _TabWidget()
        self.form_stack = self._form_stack
        self._validate_layer_maps()

        self._setup_widget_aliases()

    def _setup_widget_aliases(self) -> None:
        self.map_options = self._combo_map_options
        self.username = self._field_username
        self.password = self._field_password
        self.fname = self._field_fname
        self.lname = self._field_lname
        self.email = self._field_email
        self.pnum = self._field_pnum
        self.uname = self._field_uname
        self.pwd = self._field_pwd
        self.label_username = self._label_username
        self.paper = self._combo_paper
        self.zone_type = self._combo_zone_type
        self.nom_zone = self._field_nom_zone
        self.type_road = self._combo_type_road
        self.road_name = self._field_road_name
        self.org_cat = self._combo_org_cat
        self.org_type = self._combo_org_type
        self.org_name = self._field_org_name
        self.subd_type = self._combo_subd_type
        self.subd_name = self._field_subd_name
        self.road_ref = self._combo_road_ref
        self.num_val = self._field_num_val
        self.repetition = self._field_repetition
        self.num_state = self._combo_num_state
        self.activity_cat = self._combo_activity_cat
        self.activity_type = self._combo_activity_type
        self.mount_status = self._combo_mount_status
        self.panel_ref = self._combo_panel_ref

    def _setup_map_canvas(self) -> None:
        """Configure map canvas context menu and tool-change signals."""
        canvas = self.iface.mapCanvas()
        canvas.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        canvas.customContextMenuRequested.connect(self.on_edition_release)
        canvas.mapToolSet.connect(self._on_map_tool_changed)

    def _setup_i18n(self) -> None:
        """Clear toolbar button texts, flush i18n cache, translate combos."""
        for b in ('_btn_draw', '_btn_select', '_btn_edit', '_btn_measure'):
            btn = getattr(self, b, None)
            if btn:
                btn.setText('')
        clear_i18n_cache()
        translate_internal_combos(self)

    # ------------------------------------------------------------------
    # Signal wiring
    # ------------------------------------------------------------------

    def _populate_dispatch(self) -> None:
        _SUBMIT_DISPATCH.update(
            {
                Action.LOGIN: self.login_user,
                Action.ADD_USR: self.submit_add_usr,
                Action.RESTORE_DB: self.restore_database,
                Action.ZONE: self.add_zone,
                Action.ROAD: self.add_road,
                Action.ORG: self.add_organization,
                Action.CITY: self.add_city,
                Action.NUM: self.add_numbering,
                Action.PAN: self.add_panel,
                Action.DRAW: self.start_drawing,
                Action.SELECT: self.start_selecting,
                Action.EDIT: self.start_editing,
                Action.MEASURE: self.activate_measure,
                Action.SAVE_ACTION: lambda: on_save_action(self),
                Action.SAVE_NEW_TYPE: self._save_new_type,
                Action.LIST_ROADS: self.list_road_entries,
                Action.LIST_ORGS: self.list_organizations,
                Action.LIST_SUBDS: self.list_subdivisions,
                Action.LIST_NUMS: self.list_numberings,
                Action.LIST_PANELS: self.list_panel_signs,
            }
        )

    def _connect_signals(self) -> None:
        # Login page
        self._btn_sign_in.clicked.connect(lambda: self._on_submit(Action.LOGIN))
        self._btn_add_user.clicked.connect(lambda: self._switch_page('add_usr'))
        self._btn_restore_db.clicked.connect(lambda: self._on_submit(Action.RESTORE_DB))

        # Add User page
        self._btn_save_add.clicked.connect(lambda: self._on_submit(Action.ADD_USR))
        self._btn_cancel_add.clicked.connect(lambda: self._switch_page('login'))

        # Main page toolbar
        self._btn_gear.clicked.connect(self._toggle_settings)

        # Main page actions
        self._btn_draw.clicked.connect(lambda: self._on_submit(Action.DRAW))
        self._btn_select.clicked.connect(lambda: self._on_submit(Action.SELECT))
        self._btn_edit.clicked.connect(lambda: self._on_submit(Action.EDIT))
        self._btn_measure.clicked.connect(lambda: self._on_submit(Action.MEASURE))

        # Combo signals
        self._combo_layer_selector.currentIndexChanged.connect(self._on_layer_changed)
        self.wilaya_list.currentIndexChanged.connect(self.on_select_wilaya)
        self._combo_org_cat.currentIndexChanged.connect(self.on_select_org_cat)
        self._combo_activity_cat.currentIndexChanged.connect(
            self.on_select_activity_cat
        )
        self.feature_combo.currentIndexChanged.connect(self._on_feature_changed)
        self._combo_action.currentIndexChanged.connect(
            lambda i: on_action_changed(self, i)
        )
        self._combo_theme.currentIndexChanged.connect(
            lambda i: on_theme_changed(self, i)
        )
        self._combo_locale.currentIndexChanged.connect(
            lambda i: on_locale_changed(self, i)
        )
        self._combo_map_options.currentIndexChanged.connect(self._on_map_option_changed)

        # Save buttons
        self._btn_save_zone.clicked.connect(lambda: self._on_submit(Action.ZONE))
        self._btn_save_road.clicked.connect(lambda: self._on_submit(Action.ROAD))
        self._btn_save_org.clicked.connect(lambda: self._on_submit(Action.ORG))
        self._btn_save_city.clicked.connect(lambda: self._on_submit(Action.CITY))
        self._btn_save_num.clicked.connect(lambda: self._on_submit(Action.NUM))
        self._btn_save_pan.clicked.connect(lambda: self._on_submit(Action.PAN))
        self._btn_save_action.clicked.connect(
            lambda: self._on_submit(Action.SAVE_ACTION)
        )
        self._btn_save_new_type.clicked.connect(
            lambda: self._on_submit(Action.SAVE_NEW_TYPE)
        )

        # List buttons
        self._btn_list_roads.clicked.connect(lambda: self._on_submit(Action.LIST_ROADS))
        self._btn_list_orgs.clicked.connect(lambda: self._on_submit(Action.LIST_ORGS))
        self._btn_list_cities.clicked.connect(
            lambda: self._on_submit(Action.LIST_SUBDS)
        )
        self._btn_list_nums.clicked.connect(lambda: self._on_submit(Action.LIST_NUMS))
        self._btn_list_panels.clicked.connect(
            lambda: self._on_submit(Action.LIST_PANELS)
        )

        # Reference selection buttons
        self._btn_select_road_ref.clicked.connect(self.select_ref_handler)
        self._btn_select_panel_ref.clicked.connect(self.select_panel_ref_handler)

    def _on_submit(self, page_name: Action | str) -> None:
        if isinstance(page_name, str):
            try:
                page_name = Action(page_name)
            except ValueError:
                return
        handler = _SUBMIT_DISPATCH.get(page_name)
        if handler is not None:
            handler()
        else:
            logger.error('Unknown submit action: %s', page_name)

    def _on_map_option_changed(self, index: int) -> None:
        logger.info(
            'map_options changed: index=%d, text=%s, data=%s',
            index,
            self._combo_map_options.currentText(),
            self._combo_map_options.currentData(),
        )

    def _switch_page(self, page_name: str) -> None:
        mapping = {
            'login': 0,
            'add_usr': 1,
            'main': 2,
        }
        idx = mapping.get(page_name, 0)
        self._page_stack.setCurrentIndex(idx)

    def _toggle_settings(self) -> None:
        self._settings_visible = not self._settings_visible
        self._main_stack.setCurrentIndex(1 if self._settings_visible else 0)

    # ------------------------------------------------------------------
    # State
    # ------------------------------------------------------------------

    def _init_state(self) -> None:
        self.sat_view: str | None = None
        self.rast: str | None = None
        self.ln: str | None = None
        self.type_plan: str = ''
        self.type_to_hide: str = ''
        self.measure_tool: MeasureTool | None = None
        self.identify_tool: IdentifyTool | None = None
        self.ref_identify_tool: IdentifyTool | None = None
        self.popup_dialog: PopupDialog | None = None
        self.current_user: dict[str, Any] | None = None
        self._output_dir: str = '~/Documents'

    # ------------------------------------------------------------------
    # Feature / type management
    # ------------------------------------------------------------------

    def _on_feature_changed(self, index: int) -> None:
        main_type = self.feature_combo.itemData(index)
        if not isinstance(main_type, str):
            return
        is_activity = main_type == ACTIVITY_KEY
        self._label_subtype.setVisible(is_activity)
        self._field_new_type.setVisible(is_activity)
        fill_subtype_combo(self.subtype_combo, main_type)

    def _save_new_type(self) -> None:
        index = self.feature_combo.currentIndex()
        main_type = self.feature_combo.itemData(index)
        type_name = self._field_new_type.text().strip()
        if not type_name:
            type_name = self.subtype_combo.currentText().strip()
        category = (
            self.subtype_combo.currentData()
            if self.subtype_combo and main_type == ACTIVITY_KEY
            else ''
        )
        if save_new_type_to_json(main_type, type_name, category):
            self._field_new_type.clear()
            fill_subtype_combo(self.subtype_combo, main_type)
            clear_i18n_cache()
            count = self.subtype_combo.count()
            if count > 0:
                self.subtype_combo.setCurrentIndex(count - 1)
        else:
            QMessageBox.warning(
                self,
                self._tr('Error'),
                self._tr('Failed to save the new type.'),
            )

    # ------------------------------------------------------------------
    # Layer / form stack
    # ------------------------------------------------------------------

    def _on_layer_changed(self, index: int) -> None:
        self._form_stack.setCurrentIndex(index)
        self._update_action_button_texts(index)
        current_tab = self.menu.currentIndex()
        self.on_opt_selected(current_tab)

    @staticmethod
    def _default_layer_keys() -> list[str]:
        return ['zone', 'road', 'org', 'city', 'num', 'pan']

    def _layer_key_map(self) -> list[str]:
        """Derive layer keys from form stack widget objectNames."""
        stack = getattr(self, '_form_stack', None)
        if stack is None:
            return self._default_layer_keys()
        keys = []
        for i in range(stack.count()):
            w = stack.widget(i)
            name = w.objectName()
            if name.endswith('Form'):
                keys.append(name[:-4])
            else:
                keys.append(name)
        return keys

    def _update_action_button_texts(self, index: int) -> None:
        loc = self._tr_locale
        keys = self._layer_key_map()
        layer_key = keys[index] if 0 <= index < len(keys) else 'zone'
        draw = widget_text(f'draw_{layer_key}', loc) or 'Draw'
        select = widget_text(f'select_{layer_key}', loc) or 'Select'
        edit = widget_text(f'edit_{layer_key}', loc) or 'Edit'
        measure = widget_text('mesure_dist', loc) or 'Measure Distance'
        self._btn_draw.setText('')
        self._btn_draw.setToolTip(draw)
        self._btn_select.setText('')
        self._btn_select.setToolTip(select)
        self._btn_edit.setText('')
        self._btn_edit.setToolTip(edit)
        self._btn_measure.setText('')
        self._btn_measure.setToolTip(measure)

    LAYER_INDEX_MAP: ClassVar[list[str]] = [
        'Zones',
        'Roads',
        'Facilities',
        'Subdivisions',
        'Numbering',
        'Panels',
    ]

    def _validate_layer_maps(self) -> None:
        """Ensure LAYER_INDEX_MAP matches the form stack page count."""
        stack = getattr(self, '_form_stack', None)
        if stack is None:
            return
        count = stack.count()
        if len(self.LAYER_INDEX_MAP) != count:
            msg = (
                f'LAYER_INDEX_MAP has {len(self.LAYER_INDEX_MAP)} entries '
                f'but form stack has {count} pages'
            )
            raise AssertionError(msg)

    def _current_layer_name(self) -> str:
        idx = self._combo_layer_selector.currentIndex()
        if 0 <= idx < len(self.LAYER_INDEX_MAP):
            return self.LAYER_INDEX_MAP[idx]
        return self.LAYER_INDEX_MAP[0]

    # ------------------------------------------------------------------
    # Translation helpers
    # ------------------------------------------------------------------

    def _tr(self, source: str) -> str:
        return get_string(source, self._tr_locale)

    # ------------------------------------------------------------------
    # Theme
    # ------------------------------------------------------------------

    def apply_theme(self) -> None:
        state_apply_theme(self)
